/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.contents;

import bot.MasBot;
import javax.swing.JOptionPane;

/**
 *
 * @author Gatotkaca
 */
public class BroadcastPanel extends javax.swing.JPanel {

    /**
     * Creates new form broadcastLayout
     */
    public BroadcastPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        broadcastTextArea = new javax.swing.JTextArea();
        kirimPanel = new javax.swing.JPanel();
        kirimLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(123, 123, 132));
        setPreferredSize(new java.awt.Dimension(115, 234));

        broadcastTextArea.setColumns(20);
        broadcastTextArea.setForeground(new java.awt.Color(123, 123, 132));
        broadcastTextArea.setLineWrap(true);
        broadcastTextArea.setRows(3);
        broadcastTextArea.setMinimumSize(new java.awt.Dimension(20, 20));
        broadcastTextArea.setPreferredSize(new java.awt.Dimension(470, 180));
        jScrollPane1.setViewportView(broadcastTextArea);

        kirimPanel.setBackground(new java.awt.Color(108, 202, 255));
        kirimPanel.setPreferredSize(new java.awt.Dimension(115, 43));

        kirimLabel.setForeground(new java.awt.Color(255, 255, 255));
        kirimLabel.setText("            Kirim");
        kirimLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kirimLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kirimPanelLayout = new javax.swing.GroupLayout(kirimPanel);
        kirimPanel.setLayout(kirimPanelLayout);
        kirimPanelLayout.setHorizontalGroup(
            kirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(kirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kirimPanelLayout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(kirimLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        kirimPanelLayout.setVerticalGroup(
            kirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
            .addGroup(kirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kirimPanelLayout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(kirimLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addGap(4, 4, 4)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kirimPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kirimPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kirimLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kirimLabelMouseClicked
        MasBot masbot = new MasBot();
        String textBroadcast = broadcastTextArea.getText();
        if (masbot.sendBroadcast(textBroadcast)) {
            JOptionPane.showMessageDialog(null, "Berhasil mengirim broadcast");
            broadcastTextArea.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Gagal mengirim broadcast");
        }
        
        
    }//GEN-LAST:event_kirimLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea broadcastTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kirimLabel;
    private javax.swing.JPanel kirimPanel;
    // End of variables declaration//GEN-END:variables
}
