/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;

import views.contents.BroadcastPanel;
import views.contents.ChatPanel;
import views.contents.KeywordPanel;
import views.contents.MemberPanel;
import views.contents.UserPanel;
/**
 *
 * @author Gatotkaca
 */
public class MainFrame extends javax.swing.JFrame {
    public void setName(String name) {
        nameLabel.setText(name);
    }
    

    /**
     * @return the broadcastPanel
     */
    public BroadcastPanel getBroadcastPanel() {
        return broadcastPanel;
    }

    /**
     * @return the userPanel
     */
    public UserPanel getUserPanel() {
        return userPanel;
    }

    /**
     * @return the memberPanel
     */
    public MemberPanel getMemberPanel() {
        return memberPanel;
    }

    /**
     * @return the keywordPanel
     */
    public KeywordPanel getKeywordPanel() {
        return keywordPanel;
    }

    /**
     * @return the chatPanel
     */
    public ChatPanel getChatPanel() {
        return chatPanel;
    }

    // color pallete
    Color blue = new Color(108,202,255);
    Color white = new Color(255,255,255);
    Color grey = new Color(123,123,132);

    // content
    private BroadcastPanel broadcastPanel = new BroadcastPanel();
    private UserPanel userPanel = new UserPanel();
    private MemberPanel memberPanel = new MemberPanel();
    private KeywordPanel keywordPanel = new KeywordPanel();
    private ChatPanel chatPanel = new ChatPanel();
    
    public MainFrame() {
        initComponents();
        contentPanel.add(broadcastPanel);
        contentPanel.add(userPanel);
        contentPanel.add(memberPanel);
        contentPanel.add(keywordPanel);
        contentPanel.add(chatPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgrondPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        sidebarPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        navBroadcastPanel = new javax.swing.JPanel();
        broadcastLabel = new javax.swing.JLabel();
        navUserPanel = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        navMemberPanel = new javax.swing.JPanel();
        memberLabel = new javax.swing.JLabel();
        navKeywordPanel = new javax.swing.JPanel();
        keywordLabel = new javax.swing.JLabel();
        navChatPanel = new javax.swing.JPanel();
        chatLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgrondPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgrondPanel.setPreferredSize(new java.awt.Dimension(720, 512));

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nameLabel.setText("Username");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        sidebarPanel.setBackground(new java.awt.Color(255, 255, 255));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(195, 512));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("TELEBOT PBO");

        jLabel3.setForeground(new java.awt.Color(123, 123, 132));
        jLabel3.setText("Log Out");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        navBroadcastPanel.setBackground(new java.awt.Color(108, 202, 255));
        navBroadcastPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navBroadcastPanelMouseClicked(evt);
            }
        });

        broadcastLabel.setForeground(new java.awt.Color(255, 255, 255));
        broadcastLabel.setText("     Broadcast");

        javax.swing.GroupLayout navBroadcastPanelLayout = new javax.swing.GroupLayout(navBroadcastPanel);
        navBroadcastPanel.setLayout(navBroadcastPanelLayout);
        navBroadcastPanelLayout.setHorizontalGroup(
            navBroadcastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(broadcastLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navBroadcastPanelLayout.setVerticalGroup(
            navBroadcastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(broadcastLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        navUserPanel.setBackground(new java.awt.Color(255, 255, 255));

        userLabel.setBackground(new java.awt.Color(255, 255, 255));
        userLabel.setForeground(new java.awt.Color(123, 123, 132));
        userLabel.setText("     User");
        userLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout navUserPanelLayout = new javax.swing.GroupLayout(navUserPanel);
        navUserPanel.setLayout(navUserPanelLayout);
        navUserPanelLayout.setHorizontalGroup(
            navUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navUserPanelLayout.setVerticalGroup(
            navUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        navMemberPanel.setBackground(new java.awt.Color(255, 255, 255));
        navMemberPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navMemberPanelMouseClicked(evt);
            }
        });

        memberLabel.setBackground(new java.awt.Color(255, 255, 255));
        memberLabel.setForeground(new java.awt.Color(123, 123, 132));
        memberLabel.setText("     Member");

        javax.swing.GroupLayout navMemberPanelLayout = new javax.swing.GroupLayout(navMemberPanel);
        navMemberPanel.setLayout(navMemberPanelLayout);
        navMemberPanelLayout.setHorizontalGroup(
            navMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(memberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navMemberPanelLayout.setVerticalGroup(
            navMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(memberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        navKeywordPanel.setBackground(new java.awt.Color(255, 255, 255));
        navKeywordPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navKeywordPanelMouseClicked(evt);
            }
        });

        keywordLabel.setBackground(new java.awt.Color(255, 255, 255));
        keywordLabel.setForeground(new java.awt.Color(123, 123, 132));
        keywordLabel.setText("     Keyword");

        javax.swing.GroupLayout navKeywordPanelLayout = new javax.swing.GroupLayout(navKeywordPanel);
        navKeywordPanel.setLayout(navKeywordPanelLayout);
        navKeywordPanelLayout.setHorizontalGroup(
            navKeywordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(keywordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navKeywordPanelLayout.setVerticalGroup(
            navKeywordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(keywordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        navChatPanel.setBackground(new java.awt.Color(255, 255, 255));

        chatLabel.setBackground(new java.awt.Color(255, 255, 255));
        chatLabel.setForeground(new java.awt.Color(123, 123, 132));
        chatLabel.setText("     History Chat");
        chatLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chatLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout navChatPanelLayout = new javax.swing.GroupLayout(navChatPanel);
        navChatPanel.setLayout(navChatPanelLayout);
        navChatPanelLayout.setHorizontalGroup(
            navChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navChatPanelLayout.setVerticalGroup(
            navChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navBroadcastPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navMemberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navKeywordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navChatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(navBroadcastPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navMemberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navKeywordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navChatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        contentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout backgrondPanelLayout = new javax.swing.GroupLayout(backgrondPanel);
        backgrondPanel.setLayout(backgrondPanelLayout);
        backgrondPanelLayout.setHorizontalGroup(
            backgrondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgrondPanelLayout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgrondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        backgrondPanelLayout.setVerticalGroup(
            backgrondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgrondPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgrondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgrondPanelLayout.createSequentialGroup()
                        .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgrondPanelLayout.createSequentialGroup()
                        .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgrondPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgrondPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void navBroadcastPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navBroadcastPanelMouseClicked
        // mengganti warna background
        navBroadcastPanel.setBackground(blue);
        navUserPanel.setBackground(Color.white);
        navMemberPanel.setBackground(Color.white);
        navKeywordPanel.setBackground(Color.white);
        navChatPanel.setBackground(Color.white);

        // mengganti warna label
        broadcastLabel.setForeground(Color.white);
        userLabel.setForeground(Color.gray);
        memberLabel.setForeground(Color.gray);
        keywordLabel.setForeground(Color.gray);
        chatLabel.setForeground(Color.gray);

        // sembunyikan konten
        getBroadcastPanel().setVisible(true);
        getUserPanel().setVisible(false);
        getMemberPanel().setVisible(false);
        getKeywordPanel().setVisible(false);
        getChatPanel().setVisible(false);
    }//GEN-LAST:event_navBroadcastPanelMouseClicked

    private void userLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLabelMouseClicked
        getUserPanel().refresh();
        
        // mengganti warna background
        navUserPanel.setBackground(blue);
        navBroadcastPanel.setBackground(Color.white);
        navMemberPanel.setBackground(Color.white);
        navKeywordPanel.setBackground(Color.white);
        navChatPanel.setBackground(Color.white);

        // mengganti warna label
        userLabel.setForeground(Color.white);
        broadcastLabel.setForeground(Color.gray);
        memberLabel.setForeground(Color.gray);
        keywordLabel.setForeground(Color.gray); 
        chatLabel.setForeground(Color.gray);

        // sembunyikan konten
        getBroadcastPanel().setVisible(false);
        getUserPanel().setVisible(true);
        getMemberPanel().setVisible(false);
        getKeywordPanel().setVisible(false);
        getChatPanel().setVisible(false);
    }//GEN-LAST:event_userLabelMouseClicked

    private void navMemberPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navMemberPanelMouseClicked
        getMemberPanel().refresh();
        
        // mengganti warna background
        navMemberPanel.setBackground(blue);
        navBroadcastPanel.setBackground(Color.white);
        navUserPanel.setBackground(Color.white);
        navKeywordPanel.setBackground(Color.white);
        navChatPanel.setBackground(Color.white);

        // mengganti warna label
        memberLabel.setForeground(Color.white);
        broadcastLabel.setForeground(Color.gray);
        userLabel.setForeground(Color.gray);
        keywordLabel.setForeground(Color.gray);
        chatLabel.setForeground(Color.gray);

        // sembunyikan konten
        getBroadcastPanel().setVisible(false);
        getUserPanel().setVisible(false);
        getMemberPanel().setVisible(true);
        getKeywordPanel().setVisible(false);
        getChatPanel().setVisible(false);
    }//GEN-LAST:event_navMemberPanelMouseClicked

    private void navKeywordPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navKeywordPanelMouseClicked
        getKeywordPanel().refresh();
        
        // mengganti warna background
        navKeywordPanel.setBackground(blue);
        navBroadcastPanel.setBackground(Color.white);
        navUserPanel.setBackground(Color.white);
        navMemberPanel.setBackground(Color.white);
        navChatPanel.setBackground(Color.white);

        // mengganti warna label
        keywordLabel.setForeground(Color.white);
        broadcastLabel.setForeground(Color.gray);
        userLabel.setForeground(Color.gray);
        memberLabel.setForeground(Color.gray);
        chatLabel.setForeground(Color.gray);

        // sembunyikan konten
        getBroadcastPanel().setVisible(false);
        getUserPanel().setVisible(false);
        getMemberPanel().setVisible(false);
        getKeywordPanel().setVisible(true);
        getChatPanel().setVisible(false);
    }//GEN-LAST:event_navKeywordPanelMouseClicked

    private void chatLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatLabelMouseClicked
        getChatPanel().refresh();
        
        // mengganti warna background
        navChatPanel.setBackground(blue);
        navBroadcastPanel.setBackground(Color.white);
        navUserPanel.setBackground(Color.white);
        navMemberPanel.setBackground(Color.white);
        navKeywordPanel.setBackground(Color.white);

        // mengganti warna label
        chatLabel.setForeground(Color.white);
        broadcastLabel.setForeground(Color.gray);
        userLabel.setForeground(Color.gray);
        memberLabel.setForeground(Color.gray);
        keywordLabel.setForeground(Color.gray);

        // sembunyikan konten
        getBroadcastPanel().setVisible(false);
        getUserPanel().setVisible(false);
        getMemberPanel().setVisible(false);
        getKeywordPanel().setVisible(false);
        getChatPanel().setVisible(true);
    }//GEN-LAST:event_chatLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgrondPanel;
    private javax.swing.JLabel broadcastLabel;
    private javax.swing.JLabel chatLabel;
    private javax.swing.JLayeredPane contentPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel keywordLabel;
    private javax.swing.JLabel memberLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel navBroadcastPanel;
    private javax.swing.JPanel navChatPanel;
    private javax.swing.JPanel navKeywordPanel;
    private javax.swing.JPanel navMemberPanel;
    private javax.swing.JPanel navUserPanel;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
